### ISSUE TITLE
INFOGRAFIA

### ISSUE THREAD

**Issue by Sandra631** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Sandra631#1]
[_Infografía.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Sandra631/files/8568795/_Infografia.pdf)

**Comment by DuilioAquino10** [comment]
20/20 BUEN TRABAJO.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
